//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Server {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/Server.Data")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.Server.Classroom classroomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string firstnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lastnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.Server.Profession professionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client.Server.Classroom classroom {
            get {
                return this.classroomField;
            }
            set {
                if ((object.ReferenceEquals(this.classroomField, value) != true)) {
                    this.classroomField = value;
                    this.RaisePropertyChanged("classroom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string firstname {
            get {
                return this.firstnameField;
            }
            set {
                if ((object.ReferenceEquals(this.firstnameField, value) != true)) {
                    this.firstnameField = value;
                    this.RaisePropertyChanged("firstname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lastname {
            get {
                return this.lastnameField;
            }
            set {
                if ((object.ReferenceEquals(this.lastnameField, value) != true)) {
                    this.lastnameField = value;
                    this.RaisePropertyChanged("lastname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client.Server.Profession profession {
            get {
                return this.professionField;
            }
            set {
                if ((object.ReferenceEquals(this.professionField, value) != true)) {
                    this.professionField = value;
                    this.RaisePropertyChanged("profession");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Classroom", Namespace="http://schemas.datacontract.org/2004/07/Server.Data")]
    [System.SerializableAttribute()]
    public partial class Classroom : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Profession", Namespace="http://schemas.datacontract.org/2004/07/Server.Data")]
    [System.SerializableAttribute()]
    public partial class Profession : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserSchedule", Namespace="http://schemas.datacontract.org/2004/07/Server.Data")]
    [System.SerializableAttribute()]
    public partial class UserSchedule : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string appointmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string appointment {
            get {
                return this.appointmentField;
            }
            set {
                if ((object.ReferenceEquals(this.appointmentField, value) != true)) {
                    this.appointmentField = value;
                    this.RaisePropertyChanged("appointment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Server.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetUserById", ReplyAction="http://tempuri.org/IService/GetUserByIdResponse")]
        Client.Server.User GetUserById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetUserById", ReplyAction="http://tempuri.org/IService/GetUserByIdResponse")]
        System.Threading.Tasks.Task<Client.Server.User> GetUserByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/InsertUserIntoDb", ReplyAction="http://tempuri.org/IService/InsertUserIntoDbResponse")]
        bool InsertUserIntoDb(Client.Server.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/InsertUserIntoDb", ReplyAction="http://tempuri.org/IService/InsertUserIntoDbResponse")]
        System.Threading.Tasks.Task<bool> InsertUserIntoDbAsync(Client.Server.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/LoginUser", ReplyAction="http://tempuri.org/IService/LoginUserResponse")]
        bool LoginUser(string name, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/LoginUser", ReplyAction="http://tempuri.org/IService/LoginUserResponse")]
        System.Threading.Tasks.Task<bool> LoginUserAsync(string name, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetUserScheduleByUserId", ReplyAction="http://tempuri.org/IService/GetUserScheduleByUserIdResponse")]
        Client.Server.UserSchedule GetUserScheduleByUserId(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetUserScheduleByUserId", ReplyAction="http://tempuri.org/IService/GetUserScheduleByUserIdResponse")]
        System.Threading.Tasks.Task<Client.Server.UserSchedule> GetUserScheduleByUserIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/InsertNewUserAppointment", ReplyAction="http://tempuri.org/IService/InsertNewUserAppointmentResponse")]
        bool InsertNewUserAppointment(int id, Client.Server.UserSchedule appointment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/InsertNewUserAppointment", ReplyAction="http://tempuri.org/IService/InsertNewUserAppointmentResponse")]
        System.Threading.Tasks.Task<bool> InsertNewUserAppointmentAsync(int id, Client.Server.UserSchedule appointment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetClass", ReplyAction="http://tempuri.org/IService/GetClassResponse")]
        Client.Server.Classroom GetClass(Client.Server.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetClass", ReplyAction="http://tempuri.org/IService/GetClassResponse")]
        System.Threading.Tasks.Task<Client.Server.Classroom> GetClassAsync(Client.Server.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetClassScheduleById", ReplyAction="http://tempuri.org/IService/GetClassScheduleByIdResponse")]
        System.IO.Stream GetClassScheduleById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetClassScheduleById", ReplyAction="http://tempuri.org/IService/GetClassScheduleByIdResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> GetClassScheduleByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAllClasses", ReplyAction="http://tempuri.org/IService/GetAllClassesResponse")]
        System.Collections.Generic.List<Client.Server.Classroom> GetAllClasses();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAllClasses", ReplyAction="http://tempuri.org/IService/GetAllClassesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Client.Server.Classroom>> GetAllClassesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : Client.Server.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<Client.Server.IService>, Client.Server.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Client.Server.User GetUserById(int id) {
            return base.Channel.GetUserById(id);
        }
        
        public System.Threading.Tasks.Task<Client.Server.User> GetUserByIdAsync(int id) {
            return base.Channel.GetUserByIdAsync(id);
        }
        
        public bool InsertUserIntoDb(Client.Server.User user) {
            return base.Channel.InsertUserIntoDb(user);
        }
        
        public System.Threading.Tasks.Task<bool> InsertUserIntoDbAsync(Client.Server.User user) {
            return base.Channel.InsertUserIntoDbAsync(user);
        }
        
        public bool LoginUser(string name, string password) {
            return base.Channel.LoginUser(name, password);
        }
        
        public System.Threading.Tasks.Task<bool> LoginUserAsync(string name, string password) {
            return base.Channel.LoginUserAsync(name, password);
        }
        
        public Client.Server.UserSchedule GetUserScheduleByUserId(int id) {
            return base.Channel.GetUserScheduleByUserId(id);
        }
        
        public System.Threading.Tasks.Task<Client.Server.UserSchedule> GetUserScheduleByUserIdAsync(int id) {
            return base.Channel.GetUserScheduleByUserIdAsync(id);
        }
        
        public bool InsertNewUserAppointment(int id, Client.Server.UserSchedule appointment) {
            return base.Channel.InsertNewUserAppointment(id, appointment);
        }
        
        public System.Threading.Tasks.Task<bool> InsertNewUserAppointmentAsync(int id, Client.Server.UserSchedule appointment) {
            return base.Channel.InsertNewUserAppointmentAsync(id, appointment);
        }
        
        public Client.Server.Classroom GetClass(Client.Server.User user) {
            return base.Channel.GetClass(user);
        }
        
        public System.Threading.Tasks.Task<Client.Server.Classroom> GetClassAsync(Client.Server.User user) {
            return base.Channel.GetClassAsync(user);
        }
        
        public System.IO.Stream GetClassScheduleById(int id) {
            return base.Channel.GetClassScheduleById(id);
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> GetClassScheduleByIdAsync(int id) {
            return base.Channel.GetClassScheduleByIdAsync(id);
        }
        
        public System.Collections.Generic.List<Client.Server.Classroom> GetAllClasses() {
            return base.Channel.GetAllClasses();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Client.Server.Classroom>> GetAllClassesAsync() {
            return base.Channel.GetAllClassesAsync();
        }
    }
}
