//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Server {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/Server.Data")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.Server.Classroom classroomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string firstnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lastnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.Server.Profession professionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client.Server.Classroom classroom {
            get {
                return this.classroomField;
            }
            set {
                if ((object.ReferenceEquals(this.classroomField, value) != true)) {
                    this.classroomField = value;
                    this.RaisePropertyChanged("classroom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string firstname {
            get {
                return this.firstnameField;
            }
            set {
                if ((object.ReferenceEquals(this.firstnameField, value) != true)) {
                    this.firstnameField = value;
                    this.RaisePropertyChanged("firstname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lastname {
            get {
                return this.lastnameField;
            }
            set {
                if ((object.ReferenceEquals(this.lastnameField, value) != true)) {
                    this.lastnameField = value;
                    this.RaisePropertyChanged("lastname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client.Server.Profession profession {
            get {
                return this.professionField;
            }
            set {
                if ((object.ReferenceEquals(this.professionField, value) != true)) {
                    this.professionField = value;
                    this.RaisePropertyChanged("profession");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                if ((object.ReferenceEquals(this.usernameField, value) != true)) {
                    this.usernameField = value;
                    this.RaisePropertyChanged("username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Classroom", Namespace="http://schemas.datacontract.org/2004/07/Server.Data")]
    [System.SerializableAttribute()]
    public partial class Classroom : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int timetable_idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int timetable_id {
            get {
                return this.timetable_idField;
            }
            set {
                if ((this.timetable_idField.Equals(value) != true)) {
                    this.timetable_idField = value;
                    this.RaisePropertyChanged("timetable_id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Profession", Namespace="http://schemas.datacontract.org/2004/07/Server.Data")]
    [System.SerializableAttribute()]
    public partial class Profession : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Appointment", Namespace="http://schemas.datacontract.org/2004/07/Server.Data")]
    [System.SerializableAttribute()]
    public partial class Appointment : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string commentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime dateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int gradeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string subjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int userIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string comment {
            get {
                return this.commentField;
            }
            set {
                if ((object.ReferenceEquals(this.commentField, value) != true)) {
                    this.commentField = value;
                    this.RaisePropertyChanged("comment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime date {
            get {
                return this.dateField;
            }
            set {
                if ((this.dateField.Equals(value) != true)) {
                    this.dateField = value;
                    this.RaisePropertyChanged("date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int grade {
            get {
                return this.gradeField;
            }
            set {
                if ((this.gradeField.Equals(value) != true)) {
                    this.gradeField = value;
                    this.RaisePropertyChanged("grade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string subject {
            get {
                return this.subjectField;
            }
            set {
                if ((object.ReferenceEquals(this.subjectField, value) != true)) {
                    this.subjectField = value;
                    this.RaisePropertyChanged("subject");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int userId {
            get {
                return this.userIdField;
            }
            set {
                if ((this.userIdField.Equals(value) != true)) {
                    this.userIdField = value;
                    this.RaisePropertyChanged("userId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Server.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetUserById", ReplyAction="http://tempuri.org/IService/GetUserByIdResponse")]
        Client.Server.User GetUserById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetUserById", ReplyAction="http://tempuri.org/IService/GetUserByIdResponse")]
        System.Threading.Tasks.Task<Client.Server.User> GetUserByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetUserByName", ReplyAction="http://tempuri.org/IService/GetUserByNameResponse")]
        Client.Server.User GetUserByName(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetUserByName", ReplyAction="http://tempuri.org/IService/GetUserByNameResponse")]
        System.Threading.Tasks.Task<Client.Server.User> GetUserByNameAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/InsertUserIntoDb", ReplyAction="http://tempuri.org/IService/InsertUserIntoDbResponse")]
        bool InsertUserIntoDb(string username, string firstname, string lastname, string password, int profession_id, int class_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/InsertUserIntoDb", ReplyAction="http://tempuri.org/IService/InsertUserIntoDbResponse")]
        System.Threading.Tasks.Task<bool> InsertUserIntoDbAsync(string username, string firstname, string lastname, string password, int profession_id, int class_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/LoginUser", ReplyAction="http://tempuri.org/IService/LoginUserResponse")]
        bool LoginUser(string name, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/LoginUser", ReplyAction="http://tempuri.org/IService/LoginUserResponse")]
        System.Threading.Tasks.Task<bool> LoginUserAsync(string name, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAppointmentsByUserId", ReplyAction="http://tempuri.org/IService/GetAppointmentsByUserIdResponse")]
        System.Collections.Generic.List<Client.Server.Appointment> GetAppointmentsByUserId(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAppointmentsByUserId", ReplyAction="http://tempuri.org/IService/GetAppointmentsByUserIdResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Client.Server.Appointment>> GetAppointmentsByUserIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/InsertUserAppointment", ReplyAction="http://tempuri.org/IService/InsertUserAppointmentResponse")]
        bool InsertUserAppointment(int userId, string name, string comment, System.DateTime date, string subject, int grade);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/InsertUserAppointment", ReplyAction="http://tempuri.org/IService/InsertUserAppointmentResponse")]
        System.Threading.Tasks.Task<bool> InsertUserAppointmentAsync(int userId, string name, string comment, System.DateTime date, string subject, int grade);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetClassByUserId", ReplyAction="http://tempuri.org/IService/GetClassByUserIdResponse")]
        Client.Server.Classroom GetClassByUserId(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetClassByUserId", ReplyAction="http://tempuri.org/IService/GetClassByUserIdResponse")]
        System.Threading.Tasks.Task<Client.Server.Classroom> GetClassByUserIdAsync(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetClassScheduleById", ReplyAction="http://tempuri.org/IService/GetClassScheduleByIdResponse")]
        System.IO.Stream GetClassScheduleById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetClassScheduleById", ReplyAction="http://tempuri.org/IService/GetClassScheduleByIdResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> GetClassScheduleByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAllClasses", ReplyAction="http://tempuri.org/IService/GetAllClassesResponse")]
        System.Collections.Generic.List<Client.Server.Classroom> GetAllClasses();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAllClasses", ReplyAction="http://tempuri.org/IService/GetAllClassesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Client.Server.Classroom>> GetAllClassesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAllProfessions", ReplyAction="http://tempuri.org/IService/GetAllProfessionsResponse")]
        System.Collections.Generic.List<Client.Server.Profession> GetAllProfessions();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAllProfessions", ReplyAction="http://tempuri.org/IService/GetAllProfessionsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Client.Server.Profession>> GetAllProfessionsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAllUsers", ReplyAction="http://tempuri.org/IService/GetAllUsersResponse")]
        System.Collections.Generic.List<Client.Server.User> GetAllUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAllUsers", ReplyAction="http://tempuri.org/IService/GetAllUsersResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Client.Server.User>> GetAllUsersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetChatMessages", ReplyAction="http://tempuri.org/IService/GetChatMessagesResponse")]
        System.Collections.Generic.List<string> GetChatMessages(int amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetChatMessages", ReplyAction="http://tempuri.org/IService/GetChatMessagesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<string>> GetChatMessagesAsync(int amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/WriteToChat", ReplyAction="http://tempuri.org/IService/WriteToChatResponse")]
        void WriteToChat(string user, string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/WriteToChat", ReplyAction="http://tempuri.org/IService/WriteToChatResponse")]
        System.Threading.Tasks.Task WriteToChatAsync(string user, string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAverageGradeByUserId", ReplyAction="http://tempuri.org/IService/GetAverageGradeByUserIdResponse")]
        double GetAverageGradeByUserId(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAverageGradeByUserId", ReplyAction="http://tempuri.org/IService/GetAverageGradeByUserIdResponse")]
        System.Threading.Tasks.Task<double> GetAverageGradeByUserIdAsync(int userId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : Client.Server.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<Client.Server.IService>, Client.Server.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Client.Server.User GetUserById(int id) {
            return base.Channel.GetUserById(id);
        }
        
        public System.Threading.Tasks.Task<Client.Server.User> GetUserByIdAsync(int id) {
            return base.Channel.GetUserByIdAsync(id);
        }
        
        public Client.Server.User GetUserByName(string name) {
            return base.Channel.GetUserByName(name);
        }
        
        public System.Threading.Tasks.Task<Client.Server.User> GetUserByNameAsync(string name) {
            return base.Channel.GetUserByNameAsync(name);
        }
        
        public bool InsertUserIntoDb(string username, string firstname, string lastname, string password, int profession_id, int class_id) {
            return base.Channel.InsertUserIntoDb(username, firstname, lastname, password, profession_id, class_id);
        }
        
        public System.Threading.Tasks.Task<bool> InsertUserIntoDbAsync(string username, string firstname, string lastname, string password, int profession_id, int class_id) {
            return base.Channel.InsertUserIntoDbAsync(username, firstname, lastname, password, profession_id, class_id);
        }
        
        public bool LoginUser(string name, string password) {
            return base.Channel.LoginUser(name, password);
        }
        
        public System.Threading.Tasks.Task<bool> LoginUserAsync(string name, string password) {
            return base.Channel.LoginUserAsync(name, password);
        }
        
        public System.Collections.Generic.List<Client.Server.Appointment> GetAppointmentsByUserId(int id) {
            return base.Channel.GetAppointmentsByUserId(id);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Client.Server.Appointment>> GetAppointmentsByUserIdAsync(int id) {
            return base.Channel.GetAppointmentsByUserIdAsync(id);
        }
        
        public bool InsertUserAppointment(int userId, string name, string comment, System.DateTime date, string subject, int grade) {
            return base.Channel.InsertUserAppointment(userId, name, comment, date, subject, grade);
        }
        
        public System.Threading.Tasks.Task<bool> InsertUserAppointmentAsync(int userId, string name, string comment, System.DateTime date, string subject, int grade) {
            return base.Channel.InsertUserAppointmentAsync(userId, name, comment, date, subject, grade);
        }
        
        public Client.Server.Classroom GetClassByUserId(int userId) {
            return base.Channel.GetClassByUserId(userId);
        }
        
        public System.Threading.Tasks.Task<Client.Server.Classroom> GetClassByUserIdAsync(int userId) {
            return base.Channel.GetClassByUserIdAsync(userId);
        }
        
        public System.IO.Stream GetClassScheduleById(int id) {
            return base.Channel.GetClassScheduleById(id);
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> GetClassScheduleByIdAsync(int id) {
            return base.Channel.GetClassScheduleByIdAsync(id);
        }
        
        public System.Collections.Generic.List<Client.Server.Classroom> GetAllClasses() {
            return base.Channel.GetAllClasses();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Client.Server.Classroom>> GetAllClassesAsync() {
            return base.Channel.GetAllClassesAsync();
        }
        
        public System.Collections.Generic.List<Client.Server.Profession> GetAllProfessions() {
            return base.Channel.GetAllProfessions();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Client.Server.Profession>> GetAllProfessionsAsync() {
            return base.Channel.GetAllProfessionsAsync();
        }
        
        public System.Collections.Generic.List<Client.Server.User> GetAllUsers() {
            return base.Channel.GetAllUsers();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Client.Server.User>> GetAllUsersAsync() {
            return base.Channel.GetAllUsersAsync();
        }
        
        public System.Collections.Generic.List<string> GetChatMessages(int amount) {
            return base.Channel.GetChatMessages(amount);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<string>> GetChatMessagesAsync(int amount) {
            return base.Channel.GetChatMessagesAsync(amount);
        }
        
        public void WriteToChat(string user, string message) {
            base.Channel.WriteToChat(user, message);
        }
        
        public System.Threading.Tasks.Task WriteToChatAsync(string user, string message) {
            return base.Channel.WriteToChatAsync(user, message);
        }
        
        public double GetAverageGradeByUserId(int userId) {
            return base.Channel.GetAverageGradeByUserId(userId);
        }
        
        public System.Threading.Tasks.Task<double> GetAverageGradeByUserIdAsync(int userId) {
            return base.Channel.GetAverageGradeByUserIdAsync(userId);
        }
    }
}
