//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleClient.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/Server.Data")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SimpleClient.ServiceReference1.Classroom classroomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string firstnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lastnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SimpleClient.ServiceReference1.Profession professionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SimpleClient.ServiceReference1.Classroom classroom {
            get {
                return this.classroomField;
            }
            set {
                if ((object.ReferenceEquals(this.classroomField, value) != true)) {
                    this.classroomField = value;
                    this.RaisePropertyChanged("classroom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string firstname {
            get {
                return this.firstnameField;
            }
            set {
                if ((object.ReferenceEquals(this.firstnameField, value) != true)) {
                    this.firstnameField = value;
                    this.RaisePropertyChanged("firstname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lastname {
            get {
                return this.lastnameField;
            }
            set {
                if ((object.ReferenceEquals(this.lastnameField, value) != true)) {
                    this.lastnameField = value;
                    this.RaisePropertyChanged("lastname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SimpleClient.ServiceReference1.Profession profession {
            get {
                return this.professionField;
            }
            set {
                if ((object.ReferenceEquals(this.professionField, value) != true)) {
                    this.professionField = value;
                    this.RaisePropertyChanged("profession");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Classroom", Namespace="http://schemas.datacontract.org/2004/07/Server.Data")]
    [System.SerializableAttribute()]
    public partial class Classroom : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Profession", Namespace="http://schemas.datacontract.org/2004/07/Server.Data")]
    [System.SerializableAttribute()]
    public partial class Profession : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserSchedule", Namespace="http://schemas.datacontract.org/2004/07/Server.Data")]
    [System.SerializableAttribute()]
    public partial class UserSchedule : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string appointmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string appointment {
            get {
                return this.appointmentField;
            }
            set {
                if ((object.ReferenceEquals(this.appointmentField, value) != true)) {
                    this.appointmentField = value;
                    this.RaisePropertyChanged("appointment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetUserById", ReplyAction="http://tempuri.org/IService/GetUserByIdResponse")]
        SimpleClient.ServiceReference1.User GetUserById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetUserById", ReplyAction="http://tempuri.org/IService/GetUserByIdResponse")]
        System.Threading.Tasks.Task<SimpleClient.ServiceReference1.User> GetUserByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/InsertUserIntoDb", ReplyAction="http://tempuri.org/IService/InsertUserIntoDbResponse")]
        bool InsertUserIntoDb(SimpleClient.ServiceReference1.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/InsertUserIntoDb", ReplyAction="http://tempuri.org/IService/InsertUserIntoDbResponse")]
        System.Threading.Tasks.Task<bool> InsertUserIntoDbAsync(SimpleClient.ServiceReference1.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/LoginUser", ReplyAction="http://tempuri.org/IService/LoginUserResponse")]
        bool LoginUser(string name, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/LoginUser", ReplyAction="http://tempuri.org/IService/LoginUserResponse")]
        System.Threading.Tasks.Task<bool> LoginUserAsync(string name, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetUserScheduleByUserId", ReplyAction="http://tempuri.org/IService/GetUserScheduleByUserIdResponse")]
        SimpleClient.ServiceReference1.UserSchedule GetUserScheduleByUserId(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetUserScheduleByUserId", ReplyAction="http://tempuri.org/IService/GetUserScheduleByUserIdResponse")]
        System.Threading.Tasks.Task<SimpleClient.ServiceReference1.UserSchedule> GetUserScheduleByUserIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/InsertNewUserAppointment", ReplyAction="http://tempuri.org/IService/InsertNewUserAppointmentResponse")]
        bool InsertNewUserAppointment(int id, SimpleClient.ServiceReference1.UserSchedule appointment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/InsertNewUserAppointment", ReplyAction="http://tempuri.org/IService/InsertNewUserAppointmentResponse")]
        System.Threading.Tasks.Task<bool> InsertNewUserAppointmentAsync(int id, SimpleClient.ServiceReference1.UserSchedule appointment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetClass", ReplyAction="http://tempuri.org/IService/GetClassResponse")]
        SimpleClient.ServiceReference1.Classroom GetClass(SimpleClient.ServiceReference1.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetClass", ReplyAction="http://tempuri.org/IService/GetClassResponse")]
        System.Threading.Tasks.Task<SimpleClient.ServiceReference1.Classroom> GetClassAsync(SimpleClient.ServiceReference1.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetClassScheduleById", ReplyAction="http://tempuri.org/IService/GetClassScheduleByIdResponse")]
        System.IO.Stream GetClassScheduleById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetClassScheduleById", ReplyAction="http://tempuri.org/IService/GetClassScheduleByIdResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> GetClassScheduleByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAllClasses", ReplyAction="http://tempuri.org/IService/GetAllClassesResponse")]
        SimpleClient.ServiceReference1.Classroom[] GetAllClasses();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAllClasses", ReplyAction="http://tempuri.org/IService/GetAllClassesResponse")]
        System.Threading.Tasks.Task<SimpleClient.ServiceReference1.Classroom[]> GetAllClassesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : SimpleClient.ServiceReference1.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<SimpleClient.ServiceReference1.IService>, SimpleClient.ServiceReference1.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SimpleClient.ServiceReference1.User GetUserById(int id) {
            return base.Channel.GetUserById(id);
        }
        
        public System.Threading.Tasks.Task<SimpleClient.ServiceReference1.User> GetUserByIdAsync(int id) {
            return base.Channel.GetUserByIdAsync(id);
        }
        
        public bool InsertUserIntoDb(SimpleClient.ServiceReference1.User user) {
            return base.Channel.InsertUserIntoDb(user);
        }
        
        public System.Threading.Tasks.Task<bool> InsertUserIntoDbAsync(SimpleClient.ServiceReference1.User user) {
            return base.Channel.InsertUserIntoDbAsync(user);
        }
        
        public bool LoginUser(string name, string password) {
            return base.Channel.LoginUser(name, password);
        }
        
        public System.Threading.Tasks.Task<bool> LoginUserAsync(string name, string password) {
            return base.Channel.LoginUserAsync(name, password);
        }
        
        public SimpleClient.ServiceReference1.UserSchedule GetUserScheduleByUserId(int id) {
            return base.Channel.GetUserScheduleByUserId(id);
        }
        
        public System.Threading.Tasks.Task<SimpleClient.ServiceReference1.UserSchedule> GetUserScheduleByUserIdAsync(int id) {
            return base.Channel.GetUserScheduleByUserIdAsync(id);
        }
        
        public bool InsertNewUserAppointment(int id, SimpleClient.ServiceReference1.UserSchedule appointment) {
            return base.Channel.InsertNewUserAppointment(id, appointment);
        }
        
        public System.Threading.Tasks.Task<bool> InsertNewUserAppointmentAsync(int id, SimpleClient.ServiceReference1.UserSchedule appointment) {
            return base.Channel.InsertNewUserAppointmentAsync(id, appointment);
        }
        
        public SimpleClient.ServiceReference1.Classroom GetClass(SimpleClient.ServiceReference1.User user) {
            return base.Channel.GetClass(user);
        }
        
        public System.Threading.Tasks.Task<SimpleClient.ServiceReference1.Classroom> GetClassAsync(SimpleClient.ServiceReference1.User user) {
            return base.Channel.GetClassAsync(user);
        }
        
        public System.IO.Stream GetClassScheduleById(int id) {
            return base.Channel.GetClassScheduleById(id);
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> GetClassScheduleByIdAsync(int id) {
            return base.Channel.GetClassScheduleByIdAsync(id);
        }
        
        public SimpleClient.ServiceReference1.Classroom[] GetAllClasses() {
            return base.Channel.GetAllClasses();
        }
        
        public System.Threading.Tasks.Task<SimpleClient.ServiceReference1.Classroom[]> GetAllClassesAsync() {
            return base.Channel.GetAllClassesAsync();
        }
    }
}
